name: Build Kernel

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Host Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            libssl-dev \
            u-boot-tools \
            wget \
            bzip2 \
            tar

      - name: Setup GCC 4.8 Toolchain
        run: |
          wget -q https://releases.linaro.org/archive/14.04/components/toolchain/binaries/gcc-linaro-aarch64-linux-gnu-4.8-2014.04_linux.tar.bz2
          tar xjf gcc-linaro-aarch64-linux-gnu-4.8-2014.04_linux.tar.bz2
          echo "PATH=$(pwd)/gcc-linaro-aarch64-linux-gnu-4.8-2014.04_linux/bin:\$PATH" >> $GITHUB_ENV

      - name: Fetch Missing Header
        run: |
          cd drivers/misc/mediatek/cmdq/v2
          wget -q https://github.com/ibilux/android_device_tree_hermes/raw/crdroid-9.0/kernel-headers/cmdq_engine.h
          cd -

      - name: Copy Mediatek Headers
        run: |
          cp drivers/misc/mediatek/ext_disp/mt8167/extd_platform.h drivers/misc/mediatek/ext_disp/
          cp drivers/misc/mediatek/ext_disp/mt8167/external_display.h drivers/misc/mediatek/ext_disp/v1/
          cp drivers/misc/mediatek/thermal/mt8167/inc/*.h drivers/misc/mediatek/thermal/mt8167/
          cp -n drivers/misc/mediatek/uart/mt8167/* drivers/misc/mediatek/uart/include/
          cp -n drivers/misc/mediatek/usb11/*.h drivers/misc/mediatek/usb11/mt8167/
          cp -n drivers/misc/mediatek/video/mt8167/dispsys/*.h drivers/misc/mediatek/video/mt8167/videox/
          cp -n drivers/misc/mediatek/video/mt8167/videox/*.h drivers/misc/mediatek/video/common/

      - name: Build Kernel
        env:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          CFLAGS: "-w"
          CXXFLAGS: "-w"
        run: |
          make a04br3_defconfig
          make -j$(nproc)
          make Image dtbs -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/mediatek/a04br3.dtb
            arch/arm64/boot/Image.gz
            arch/arm64/boot/Image.gz-dtb
